export const MOST_FAMOUS_QUOTES: string[] = [
  "Imagination is more important than knowledge.",
  "You must be the change you want to see in the world.",
  "The two most important days in your life are the day you are born and the day you find out why.",
  "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.",
  "Education is the most powerful weapon which you can use to change the world.",
  "I have not failed. I've just found 10,000 ways that won't work.",
  "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.",
  "All the world's a stage, and all the men and women merely players.",
  "Spread love everywhere you go. Let no one ever come to you without leaving happier.",
  "In the depth of winter, I finally learned that there was in me an invincible summer.",
  "No one can make you feel inferior without your consent.",
  "The only way to do great work is to love what you do.",
  "It does not matter how slowly you go as long as you do not stop.",
  "Life is really simple, but we insist on making it complicated.",
  "The only thing we have to fear is fear itself.",
  "Happiness is not something ready made. It comes from your own actions.",
  "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
  "I have a dream...",
  "You miss 100% of the shots you don't take.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "The only limit to our realization of tomorrow will be our doubts of today.",
  "Our greatest glory is not in never falling, but in rising every time we fall.",
  "In three words I can sum up everything I've learned about life: it goes on.",
  "You can't use up creativity. The more you use, the more you have.",
  "Life is what happens when you're busy making other plans.",
  "The only thing necessary for the triumph of evil is for good men to do nothing.",
  "You are never too old to set another goal or to dream a new dream.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "It's not the years in your life that count. It's the life in your years.",
  "To succeed in life, you need two things: ignorance and confidence.",
  "The best revenge is massive success.",
  "The only person you should try to be better than is the person you were yesterday.",
  "You can complain because roses have thorns, or you can rejoice because thorns have roses.",
  "The journey of a thousand miles begins with one step.",
  "In the middle of every difficulty lies opportunity.",
  "Don't count the days, make the days count.",
  "Believe you can and you're halfway there.",
  "You have power over your mind, not outside events. Realize this, and you will find strength.",
  "The only true wisdom is in knowing you know nothing.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall.",
  "The purpose of our lives is to be happy.",
  "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.",
  "The best way to predict the future is to create it.",
  "It's not what happens to you, but how you react to it that matters.",
  "Life is short, and it is up to you to make it sweet.",
  "Don't watch the clock; do what it does. Keep going.",
  "I find that the harder I work, the more luck I seem to have.",
  "The only impossible journey is the one you never begin.",
  "If you want to lift yourself up, lift up someone else.",
  "The secret of getting ahead is getting started.",
  "The biggest risk is not taking any risk. In a world that's changing quickly, the only strategy that is guaranteed to fail is not taking risks.",
  "The harder I work, the luckier I get.",
  "In the end, it's not the years in your life that count. It's the life in your years.",
  "Dream big and dare to fail.",
];
